# Generated by Django 4.2.4 on 2023-08-23 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, verbose_name='Slug')),
                ('status', models.SmallIntegerField(choices=[(1, 'Nouveau'), (2, 'Ouvert'), (3, 'Fermé'), (4, 'Résolu')], default=1, verbose_name='Status')),
                ('description', models.TextField(verbose_name='More details')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/main/attachments/%Y/%m/', verbose_name='Attachment')),
                ('rating_stars', models.SmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Review')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='UUID')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assignee')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-date', 'subject', 'status', 'rating_stars'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/comments/attachments/%Y/%m/', verbose_name='Attachment')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_support_tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-date', 'ticket', 'author', 'is_active'],
            },
        ),
    ]
